name: "CD"

on:
  schedule:
    # twice per month
    - cron: "10 5 1,14 * *"
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  Testing:
    strategy:
      matrix:
        version: ['8.2', '8.3']
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        target: test-runner
        tags: php${{ matrix.version }}-checks
        build-args: PHP_VERSION=${{ matrix.version }}
    - name: Run tests
      run: docker run php${{ matrix.version }}-checks sh -c "composer test:all"
  Deploy:
    needs: Testing
    strategy:
      matrix:
        os-variant: ['jammy', 'noble', 'bookworm', 'alpine']
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout code
      uses: actions/checkout@v4
    - 
      name: Build testing Docker Image
      uses: docker/build-push-action@v5
      with:
        push: false
        file: ./Dockerfile
        context: ./
        target: dist
        tags: testing
        build-args: OS_VARIANT=${{ matrix.os-variant }}
    - 
      name: Set up QEMU (multiplatform)
      uses: docker/setup-qemu-action@v3
    - 
      name: Set up Docker Buildx (multiplatform)
      uses: docker/setup-buildx-action@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Prepare image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/message-broker
        tags: |
          type=raw,value=${{ matrix.os-variant }}
          type=semver,pattern={{version}},suffix=-${{ matrix.os-variant }}
          type=semver,pattern={{major}},suffix=-${{ matrix.os-variant }}
          type=semver,pattern={{major}}.{{minor}},suffix=-${{ matrix.os-variant }}
          type=semver,pattern={{version}},enable=${{ 'jammy' == matrix.os-variant }}
          type=semver,pattern={{major}},enable=${{ 'jammy' == matrix.os-variant }}
          type=semver,pattern={{major}}.{{minor}},enable=${{ 'jammy' == matrix.os-variant }}
          type=raw,value=latest,enable=${{ 'jammy' == matrix.os-variant }}
    - 
      name: Build & push to Docker Hub
      uses: docker/build-push-action@v5
      with:
        push: true
        file: ./Dockerfile
        context: ./
        platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
        target: dist
        tags: ${{ steps.meta.outputs.tags }},
        labels: ${{ steps.meta.outputs.labels }},
        build-args: OS_VARIANT=${{ matrix.os-variant }}
