name: "CI"

on:
  push:
    branches:
      - '**'
  # workflow can be called directly
  workflow_call:
    
jobs:

  Testing:
    strategy:
      matrix:
        version: ['8.2', '8.3']
        os-variant: ['jammy', 'noble', 'bookworm', 'alpine']
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build docker image
      uses: docker/build-push-action@v5
      with:
        push: false
        target: test-runner
        tags: php${{ matrix.version }}-${{ matrix.os-variant}}-checks
        build-args: |
          PHP_VERSION=${{ matrix.version }}
          OS_VARIANT=${{ matrix.os-variant }}
    - name: Run all tests
      run: docker run --rm -v ./:/var/www/html/public/build php${{ matrix.version }}-${{ matrix.os-variant}}-checks sh -c "composer test:all"
    - name: Generate coverage badge
      uses: timkrase/phpunit-coverage-badge@v1.2.1
      with:
        coverage_badge_path: 'badge-coverage.svg'
        push_badge: true
