name: "CI"

on:
  pull_request:
  push:
    branches:
      - '**'
  # workflow can be called directly
  workflow_call:
    
jobs:

  Testing:
    strategy:
      matrix:
        version: ['8.2', '8.3']
        os-variant: ['jammy', 'noble', 'bookworm', 'alpine']
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build test runner
      uses: docker/build-push-action@v5
      with:
        push: false
        target: test-runner
        tags: php${{ matrix.version }}-${{ matrix.os-variant}}-checks
        build-args: |
          PHP_VERSION=${{ matrix.version }}
          OS_VARIANT=${{ matrix.os-variant }}
    - name: Run all tests
      run: docker run --rm php${{ matrix.version }}-${{ matrix.os-variant}}-checks sh -c "composer test:all"
    - name: Build dist image
      uses: docker/build-push-action@v5
      with:
        push: false
        target: dist
        build-args: PHP_VERSION=${{ matrix.version }}
